In [ ]:
!pip install hf_xet

Requirement already satisfied: hf_xet in /usr/local/lib/python3.12/dist-packages (1.4.3)

In [ ]:
import pandas as pd
import numpy as np
import torch
from transformers import pipeline
from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig

In [ ]:
if torch.cuda.is_available():
    device = "cuda"
elif torch.backends.mps.is_available():
    device = "mps"
else:
    device = "cpu"
print(f"Using device: {device}")

Using device: cuda

Load a model and tokenizer for the SmolLM2 small model from HuggingFace 🤗

In [ ]:
model_name="HuggingFaceTB/SmolLM2-360M-Instruct"

In [ ]:
model = AutoModelForCausalLM.from_pretrained(model_name, device_map="auto")
tokenizer = AutoTokenizer.from_pretrained(model_name)

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:93: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

config.json:   0%|          | 0.00/846 [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

model.safetensors:   0%|          | 0.00/724M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/290 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/132 [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/655 [00:00<?, ?B/s]

The tokenizer converts a string to a 2D tensor of tokens.

In [ ]:
model_inputs = tokenizer.encode("A list of colors: red, blue")
model_inputs

[49, 1398, 282, 4683, 42, 2382, 28, 4461]

We can decode these token IDs one by one using the tokenizer `decode` method

In [ ]:
[tokenizer.decode(token_id) for token_id in model_inputs]

['A', ' list', ' of', ' colors', ':', ' red', ',', ' blue']

To generate a continuation of a prompt, we tokenize the prompt using PyTorch tensors, and feed this into the model created above.

In [ ]:
model_inputs = tokenizer(["A sequence of numbers: 2, 4, 8, 14"], return_tensors="pt").to(device)
print(model_inputs)
generated_ids = model.generate(**model_inputs, max_new_tokens=20)
print(generated_ids)
tokenizer.decode(generated_ids[0], skip_special_tokens=True)

## Looking at the logits

Request a continuation from the model, with `output_logits=True`,and `return_dict_in_generate=True`. Note you need both options.

In [ ]:
model_inputs = tokenizer(["Continue the sequence of numbers: 2, 4, 8"], return_tensors="pt").to(device)
model_output = model.generate(**model_inputs, max_new_tokens=20, do_sample=False, output_logits=True, return_dict_in_generate=True)

The output token IDs are contained in `model_output.sequences`

In [ ]:
model_output.sequences[0]

tensor([26226,   260,  5972,   282,  2966,    42,   216,    34,    28,   216,
           36,    28,   216,    40,    28,   216,    33,    38,    28,   216,
           35,    34,    28,   216,    38,    36,    28,   216,    33,    34,
           40,    28,   216,    34])

The output logits for each step are contained in the tuple `model_output.logits` each entry is a tensor of $\text{bach_dim} \times \text{vocab_size}$ dimensions

In [ ]:
model_output.logits[0].shape

torch.Size([1, 49152])

The output can be reconstructed from the token IDs using tokenizer functions

In [ ]:
tokenizer.decode(model_output.sequences[0])

'Continue the sequence of numbers: 2, 4, 8, 16, 32, 64, 128, 2'

Let's pack the output logits into a numpy array

In [ ]:
output_len = len(model_output.logits)
output_logits = np.array([model_output.logits[k][0].cpu() for k in range(output_len)])

The greedy-decoding results is the maximum logit at each postion in the sequence (as we are using greedy decoding), namely the maximum index over the second (token) axis

In [ ]:
output_tokens = [tokenizer.decode(t) for t in output_logits.argmax(axis=1)]
"".join(output_tokens)

', 16, 32, 64, 128, 2'

The greedy-decoding results is the maximum logit at each postion in the sequence (as we are using greedy decoding), namely the maximum index over the second (token) axis

In [ ]:
output_token_ids = output_logits.argmax(axis=1)
np.allclose(output_token_ids, model_output.sequences[0, -output_len:].cpu())

True

In [ ]:
def show_logits_with_color_scale(model_output, logits_processor=None, num_top_tokens=15):
    def color_scale(val, min_val, max_val):
        if isinstance(val, str):
            return ''

        # Normalize the value to the range [0, 1]
        normalized_val = (val - min_val) / (max_val - min_val) if (max_val - min_val) != 0 else 0

        # Calculate the RGB values based on the normalized value
        # Transition from blue to red
        red = int(255 * normalized_val)
        blue = int(255 * (1 - normalized_val))
        green = int(150 * normalized_val)

        # Highlight if max value
        return f'background-color: rgb({red}, {green}, {blue});'

    def maximum_value_in_column(column):
        highlight = 'color: white; font-weight: bold'
        default = ''
        maximum_in_column = column.max()

        # must return one string per cell in this column
        return [highlight if v == maximum_in_column else default for v in column]

    output_len = len(model_output.logits)
    input_len = len(model_output.sequences[0]) - output_len
    if logits_processor:
        output_logits = np.array([logits_processor(model_output.sequences[:,:input_len+k], model_output.logits[k])[0].cpu() for k in range(output_len)])
    else:
        output_logits = np.array([model_output.logits[k][0].cpu() for k in range(output_len)])

    output_idx = output_logits.argmax(axis=1)
    output_tokens = [tokenizer.decode(t) for t in output_idx]

    logits_idx_top = output_logits.max(axis=0).argsort()[-num_top_tokens:]
    logits_idx_top = sorted([int(idx) for idx in set(logits_idx_top).union(output_idx)])

    token_str_top = [tokenizer.decode(t) for t in logits_idx_top]
    column_index = pd.MultiIndex.from_tuples([(i, token) for i, token in enumerate(output_tokens)], names=['index', 'token'])

    df = pd.DataFrame(output_logits[:, logits_idx_top].T, index=[repr(s.encode('utf-8'))[1:] for s in token_str_top], columns=column_index)

    # Apply the styling
    styled_df = df.style.map(lambda x: color_scale(x, df.min().min(), df.max().max()), subset=df.columns)
    styled_df.apply(maximum_value_in_column, axis=0)

    # Format values to two decimal places
    styled_df = styled_df.format("{:.2f}")

    return styled_df

It's interesting to compare the logits for a sequence that it gets right, and notice that the difference between highest and next highest answer are considerably higher for the case where it has the right answer (the more known sequence), especially for the second digit

In [ ]:
model_inputs = tokenizer(["Continue the sequence of numbers: 2, 4, 8"], return_tensors="pt").to(device)
model_output = model.generate(**model_inputs, max_new_tokens=20, do_sample=False, output_logits=True, return_dict_in_generate=True)

In [ ]:
show_logits_with_color_scale(model_output)

## Logit Processors

Let's try some logit processing. Tis code is modified from (ReLLM)[https://github.com/r2d4/rellm] and supresses tokens not in `allowed_token_ids` from being generated by subtracting a number from their logits.

In [ ]:
from transformers import LogitsProcessor

class LogitsMask(LogitsProcessor):
    def __init__(self, allowed_token_ids):
        self.allowed_token_ids = set(allowed_token_ids)

    def __call__(self, input_ids, scores):
        mask = torch.ones_like(scores) * -10
        for token_id in self.allowed_token_ids:
            mask[:, token_id] = 0
        scores = scores + mask
        return scores

Let's define numeric tokens that we want the model to preference. Note that the SmolLM2 model tokenizer converts individual numbers to tokens and there are no multi-character tokens containing numbers. We can confirm this by searching the entire vocab for tokens with numbers in them:

In [ ]:
import regex
re_num = regex.compile(r".*(\d+).*")
[v for v in tokenizer.get_vocab().keys() if re_num.match(v)]

['9', '6', '3', '0', '1', '4', '7', '8', '5', '2']

Let's allow only even numbers and see how the output changes

In [ ]:
allowed_tokens = list("0123456789 ")
allowed_token_ids = [tokenizer.encode(t)[0] for t in allowed_tokens] + [tokenizer.eos_token_id]
lm_test = LogitsMask(allowed_token_ids)

In [ ]:
allowed_token_ids

[32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 216, 2]

In [ ]:
model_inputs = tokenizer(["Continue the sequence of numbers: 2, 4, 8"], return_tensors="pt").to(device)
model_output = model.generate(**model_inputs, max_new_tokens=20, logits_processor=[lm_test], do_sample=False, output_logits=True, return_dict_in_generate=True)

In [ ]:
show_logits_with_color_scale(model_output, lm_test)

## Constraining to a RegEx

We want to test at generation step if the generated string up to now appended by each token string in the vocabulary would be valid.

Tchis requires a partial match, where the regex processor returns valid if the supplied string is consistent with the RegEx pattern so far.  This is provided in the python regex library (but not the inbuilt re library).

RegEx is based on [this thread](https://stackoverflow.com/questions/3809401/what-is-a-good-regular-expression-to-match-a-url#3809435)

In [ ]:
import regex
regex_http = regex.compile(" ?https?:\/\/(www\.)?\w{1,256}\.\w{1,6}(?:(/|\\?|#)[^\\s]*)?$")

print(regex_http.match("http://test.com/sdas"))
print(regex_http.match("http://test."))
print(regex_http.match("http://test.", partial=True))
print(regex_http.match("http://test.$$$", partial=True))

<regex.Match object; span=(0, 20), match='http://test.com/sdas'>
None
<regex.Match object; span=(0, 12), match='http://test.', partial=True>
None

In [ ]:
print(regex_http.match("http://test.com/sdas\ntest"))

None

Let's try a parser that's given the string up to this point, and multiple tokens, and then uses regex to check the tokens that would complete the string

In [ ]:
from transformers import LogitsProcessor

class RegexMask(LogitsProcessor):
    def __init__(self, regex, tokenizer, stop_on_match=False, subtract_on_mask=10):
        self.regex = regex
        self.tokenizer = tokenizer
        self.vocab_map = {token_id: tokenizer.decode(token_id) for _, token_id in tokenizer.get_vocab().items()}
        self.first_in_sequence = None
        self.stop_on_match = stop_on_match
        self.subtract_on_mask = subtract_on_mask
        self.debug = False

    def reset(self):
        self.first_in_sequence = None

    def __call__(self, input_ids, scores):
        if self.first_in_sequence is None:
            self.first_in_sequence = input_ids.shape[1]
            partial_output_str = ''
        else:
            partial_output_str = self.tokenizer.decode(input_ids[0, self.first_in_sequence:])

        # Always allow the model to finish (even if not valid)
        allowed_token_ids = []

        if self.debug:
            print(f"current: {partial_output_str}")

        # Search through all tokens to see which could give a match to the regex
        for token_id, token_str in self.vocab_map.items():
            if self.regex.match(partial_output_str + token_str, partial=True):
                allowed_token_ids.append(token_id)

        # Force the model to finish when valid
        if self.stop_on_match and self.regex.match(partial_output_str):
            allowed_token_ids = [self.tokenizer.eos_token_id]
        else:
            allowed_token_ids += [self.tokenizer.eos_token_id]

        if self.debug:
            print(f"num allowed tokens: {len(allowed_token_ids)}")

        # Mask scores for tokens that don't match regex
        mask = -self.subtract_on_mask * torch.ones_like(scores)
        for token_id in allowed_token_ids:
            mask[:, token_id] = 0
        scores = scores + mask
        return scores

Example

In [ ]:
prompt = ["One of the most common web addresses is:"]

In [ ]:
logits_http_mask = RegexMask(regex_http, tokenizer, stop_on_match=True)
model_inputs = tokenizer(prompt, return_tensors="pt").to(device)
model_output = model.generate(**model_inputs, max_new_tokens=15, do_sample=False, output_logits=True, return_dict_in_generate=True)
decoded_output = tokenizer.batch_decode(model_output.sequences, skip_special_tokens=True)[0]
print(f"--------\n{decoded_output}\n--------")

--------
One of the most common web addresses is:

www.google.com

This is a well-known
--------

In [ ]:
logits_http_mask = RegexMask(regex_http, tokenizer, stop_on_match=True)
model_inputs = tokenizer(prompt, return_tensors="pt").to(device)
model_output = model.generate(**model_inputs, max_new_tokens=20, logits_processor=[logits_http_mask], do_sample=False, output_logits=True, return_dict_in_generate=True)
decoded_output = tokenizer.batch_decode(model_output.sequences, skip_special_tokens=True)[0]
print(f"--------\n{decoded_output}\n--------")

logits_http_mask.reset()
show_logits_with_color_scale(model_output, logits_http_mask)

--------
One of the most common web addresses is: http://www.google.com
--------

Notice the difference when we include the http: in the prompt. The model can no longer choose the token `://` and this affects the rest of the output, the model putting spaces throughout the address

In [ ]:
model_inputs = tokenizer(["One of the most common web addresses is: http:"], return_tensors="pt").to(device)
model_output = model.generate(**model_inputs, max_new_tokens=20, do_sample=False, output_logits=True, return_dict_in_generate=True)
decoded_output = tokenizer.batch_decode(model_output.sequences, skip_special_tokens=True)[0]
print(f"--------\n{decoded_output}\n--------")

--------
One of the most common web addresses is: http: // www. google. com . This is the address of the Google search engine.

Another
--------

If we enforce constrained generation, the model completes the web address without spaces even though it needs to split the tokens `:` and `//` which it likely hasn't seen before in training.

Note here we need to backtrack the `first_in_sequence` to start with the `http` token in the input. This is dependent on the tokenizer, and again this code is just for exploration and learning, don't do this in real code!

In [ ]:
logits_http_mask = RegexMask(regex_http, tokenizer, subtract_on_mask=10)
model_inputs = tokenizer(["One of the most common web addresses is: http:"], return_tensors="pt").to(device)
logits_http_mask.first_in_sequence = model_inputs.input_ids.shape[1]-2
model_output = model.generate(**model_inputs, max_new_tokens=20, logits_processor=[logits_http_mask], do_sample=False, output_logits=True, return_dict_in_generate=True)
decoded_output = tokenizer.batch_decode(model_output.sequences, skip_special_tokens=True)[0]
print(f"--------\n{decoded_output}\n--------")

logits_http_mask.first_in_sequence = model_inputs.input_ids.shape[1]-2
show_logits_with_color_scale(model_output, logits_http_mask)

--------
One of the most common web addresses is: http://www.google.com/

--------

With constrained generation we are not restricted to greedy sampling, we can use multi-nomial sampling of the masked logits to generate different outputs:

In [ ]:
logits_http_mask = RegexMask(regex_http, tokenizer, subtract_on_mask=torch.inf)
model_inputs = tokenizer(["One of the most common web addresses is: "], return_tensors="pt").to(device)

for ii in range(10):
    logits_http_mask.reset()
    model_output = model.generate(**model_inputs, max_new_tokens=20, logits_processor=[logits_http_mask], do_sample=True, output_logits=True, return_dict_in_generate=True)
    print(tokenizer.batch_decode(model_output.sequences, skip_special_tokens=True)[0])

One of the most common web addresses is:  http://www.google.com/

One of the most common web addresses is:  http://example.com/.

One of the most common web addresses is:  http://www.example.com

One of the most common web addresses is:  http://www.google.com/.

One of the most common web addresses is:  http://www.example.com

One of the most common web addresses is:  http://www.google.com

One of the most common web addresses is:  https://www.google.com/

One of the most common web addresses is:  https://www.google.com/about

One of the most common web addresses is:  http://username.net/your/document

One of the most common web addresses is:  http://www.example.com